### ISSUE TITLE
Unable to Slice in Cura 5.2.1

### ISSUE THREAD

**Issue by frankt2012** [jjgraphix/KlipperSettingsPlugin#2]
When using Pressure Advance Tuning Tower Preset with Apply Suggested Settings in Cura 5.2.1 I get unable to slice error. Seems to be referring to something to do with what the plugin is changing in settings.

**Comment by jjgraphix** [comment]
> When using Pressure Advance Tuning Tower Preset with Apply Suggested Settings in Cura 5.2.1 I get unable to slice error. Seems to be referring to something to do with what the plugin is changing in settings.

I've attempted to recreate this but everything seems to be working fine in Cura 5.2.1. However, keep in mind that you still must manually set the _Tuning Tower Factor_ even with when applying suggested settings. Since there's no accurate way for me to determine an appropriate value for the user's extruder, the Klipper recommendations are displayed when the tuning tower is enabled:

![image](https://user-images.githubusercontent.com/51905518/212532565-0576c799-6927-4ded-b8a9-b46b23cf5962.png)

_Otherwise it will prevent you from slicing but should indicate the problematic value:_

![image](https://user-images.githubusercontent.com/51905518/212531667-4bdc363c-0f21-4951-9c13-984a0aa5d92c.png)

This is also why it doesn't currently increase the layer width automatically as this depends on the user's setup but it does suggest values for the current nozzle size in Cura. I've considered adding a separate option to select if a direct drive or bowden tube extruder is being used but I fear it's only adding unneeded complexity. If others feel it'll be helpful, I'll revisit this in the future.

**If you're experiencing a different problem, please reply with a screenshot of the error. Otherwise I will consider this resolved.**

Thank you.

**Comment by frankt2012** [comment]
> > When using Pressure Advance Tuning Tower Preset with Apply Suggested Settings in Cura 5.2.1 I get unable to slice error. Seems to be referring to something to do with what the plugin is changing in settings.
> 
> I've attempted to recreate this but everything seems to be working fine in Cura 5.2.1. However, keep in mind that you still must manually set the _Tuning Tower Factor_ even when applying suggested settings. Since there's no accurate way for me to determine an appropriate value for the user's extruder, the Klipper recommendations are displayed when the tuning tower is enabled:
> 
> ![image](https://user-images.githubusercontent.com/51905518/212532565-0576c799-6927-4ded-b8a9-b46b23cf5962.png)
> 
> _Otherwise it will prevent you from slicing but should indicate the problematic value:_
> 
> ![image](https://user-images.githubusercontent.com/51905518/212531667-4bdc363c-0f21-4951-9c13-984a0aa5d92c.png)
> 
> This is also why it does not currently increase print speed and layer height automatically. This depends on the user's setup but it does suggest values for the current nozzle size in Cura. I've considered adding a separate option to select if a direct drive or bowden tube extruder is being used but I fear it's only adding unneeded complexity. If others feel it'll be helpful, I'll revisit this in the future.
> 
> **If you're experiencing a different problem, please reply with a screenshot of the error. Otherwise I will consider this resolved.**
> 
> Thank you.

I don't know what I did wrong when I tried this plugin last month but just reinstalled it and it works perfectly. Sorry for the trouble. Thank you.
