### ISSUE TITLE
Missing PA for top surface skin

### ISSUE THREAD

**Issue by otymm** [jjgraphix/KlipperSettingsPlugin#6]
Seperate pressure advance settings are available for all parts of the print except top surface skin (top/bottom does exist).

**Comment by jjgraphix** [comment]
The top/bottom option should apply to the top surface skin. Unfortunately, due to how Cura annotates the gcode there isn't an accurate way to detect where the top surface skin is. This is likely why it's not an option in the linear advance plugin either.

If I added an option that applies it to the last skin of the print any top surface of the model printed prior to this would still have to use the top/bottom option. There is a potential, crude solution I was experimenting with and if I find a way to accomplish it accurately (or if Cura improves the gcode annotations) I'll add the option but until then you'll need to use top/bottom for this.
